### ISSUE TITLE
Incompatibility bug of the sale_order_invoice_date module with the POS module

### ISSUE THREAD

**Issue by majouda** [OCA/sale-reporting#242]
## Module
The name of the module that has a bug.
sale_order_invoice_date

## Describe the bug
Incompatibility bug of the sale_order_invoice_date module with the POS module

## To Reproduce
**Affected versions**: 14.0

1. Install POS module
2. Install sale_order_invoice_date, an error will appear
3. 

**Expected behavior**
To be able to install the module "sale_order_invoice_date" while POS module is installed

**Additional context**

The error message:
File "/usr/local/lib/python3.8/site-packages/odoo/addons/sale/report/sale_report.py", line 168, in init
    self.env.cr.execute("""CREATE or REPLACE VIEW %s as (%s)""" % (self._table, self._query()))
  File "<decorator-gen-3>", line 2, in execute
  File "/usr/local/lib/python3.8/site-packages/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/odoo/sql_db.py", line 301, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.SyntaxError: each UNION query must have the same number of columns
LINE 71:             -MIN(l.id) AS id,
                     ^

**Comment by TumbaoJu** [comment]
@ivantodorovich : Could you please look into this issue.
Thank you in advance.

**Comment by TumbaoJu** [comment]
@simahawk
Hello!  Can you help with this issue?  We would like to know what to do to have it proceeded.
Thank you ;)

**Comment by ivantodorovich** [comment]
Unfortunately, this module is incompatible with the POS.

This is due to the ugly integration of Point of Sale Orders into the Sale Report module done by upstream `pos_sale` module ([ref](https://github.com/odoo/odoo/blob/14.0/addons/pos_sale/report/sale_report.py))

A possible workaround would be to create a "glue" module to implement this "invoice_date" field to data coming from pos orders, or at least add an empty column in its place.

Note that this would happen for any module adding new fields to the Sale Analysis report. It's an architectural flaw

**Comment by TumbaoJu** [comment]
@ivantodorovich : Thank you for your answer.
